from __future__ import annotations
import argparse, json, sys
from pathlib import Path
from . import __version__
from .doctor import snapshot, as_json
from .runner import run_command
from .report import render
from .bundle import make_bundle
from .minimize import minimize_spec
from .demo import sample_report
from .torchtrace import run_script
from .compare import compare_commands

BLUE='\033[94m'; CYAN='\033[96m'; GREEN='\033[92m'; YELLOW='\033[93m'; BOLD='\033[1m'; DIM='\033[2m'; RESET='\033[0m'

def _tty(s):
    return s if sys.stdout.isatty() else s.replace(BLUE,'').replace(CYAN,'').replace(GREEN,'').replace(YELLOW,'').replace(BOLD,'').replace(DIM,'').replace(RESET,'')

def echo(s=''):
    print(_tty(s))

def _doctor(json_mode=False):
    if json_mode:
        print(as_json()); return 0
    s=snapshot()
    echo(f"{BOLD}KernelWitness {__version__}{RESET}")
    echo(f"{s.platform} · Python {s.python}\n")
    echo(f"{'tool':20} {'status':12} version")
    echo('-'*72)
    for x in s.tools:
        status=f"{GREEN}available{RESET}" if x.available else f"{DIM}missing{RESET}"
        echo(f"{x.name:20} {status:21} {x.version}")
    if s.gpu:
        echo(f"\n{GREEN}GPU{RESET} {s.gpu.get('name','unknown')}  cc {s.gpu.get('compute_capability','?')}")
    return 0

def _run(args):
    cmd=args.command
    if cmd and cmd[0]=='--': cmd=cmd[1:]
    if not cmd:
        raise SystemExit('kernelwitness run requires a command after --')
    echo(f"{CYAN}KernelWitness{RESET} recording {BOLD}{' '.join(cmd)}{RESET}")
    r=run_command(cmd,args.attempts,args.timeout,args.sanitizer,args.coredump,args.out)
    render(r,args.out); bundle=make_bundle(r,args.out)
    echo(f"\n{BOLD}{r.classification.title}{RESET}  reproduced {YELLOW}{r.reproduced}/{r.total_attempts}{RESET}")
    echo(f"report  {Path(args.out)/'index.html'}")
    echo(f"bundle  {bundle}")
    return 1 if r.reproduced else 0

def _minimize(args):
    r=minimize_spec(args.spec,args.out)
    echo(f"{GREEN}{BOLD}Minimal reproducer found{RESET}")
    for k,v in r.parameters.items(): echo(f"{k:>14}  {v}")
    echo(f"\n{' '.join(r.command)}\noutput  {args.out}")
    return 0

def _demo(args):
    r=sample_report(); render(r,args.out); make_bundle(r,args.out)
    echo(f"demo report  {Path(args.out)/'index.html'}")
    return 0

def _export(args):
    data=json.loads(Path(args.report).read_text())
    cls=data['classification']; env=data['environment']; cmd=data['command']
    md=(
      "### KernelWitness reproduction\n\n"
      f"- **Failure:** {cls['title']} (`{cls['kind']}`)\n"
      f"- **Reproduction:** {data['reproduced']}/{data['total_attempts']}\n"
      f"- **GPU:** {env.get('gpu',{}).get('name','No NVIDIA GPU detected')}\n"
      f"- **Command:** `{' '.join(cmd)}`\n\n"
      "Generated by [KernelWitness](https://github.com/mneha05/kernelwitness).\n"
    )
    if args.out: Path(args.out).write_text(md); echo(args.out)
    else: print(md)
    return 0

def main(argv=None):
    p=argparse.ArgumentParser(prog='kernelwitness',description='Turn GPU failures into minimal, shareable repro bundles.')
    p.add_argument('--version',action='version',version=__version__)
    sp=p.add_subparsers(dest='sub',required=True)
    d=sp.add_parser('doctor',help='inspect GPU debugging environment'); d.add_argument('--json',action='store_true')
    r=sp.add_parser('run',help='record and classify a failing command'); r.add_argument('--attempts',type=int,default=3); r.add_argument('--timeout',type=float,default=120); r.add_argument('--sanitizer',choices=['none','auto','memcheck','racecheck','initcheck','synccheck'],default='none'); r.add_argument('--coredump',action='store_true'); r.add_argument('--out',default='kernelwitness-report'); r.add_argument('command',nargs=argparse.REMAINDER)
    m=sp.add_parser('minimize',help='shrink a parameterized reproducer'); m.add_argument('spec'); m.add_argument('--out',default='kernelwitness-minimized')
    de=sp.add_parser('demo',help='generate an offline sample report'); de.add_argument('--out',default='kernelwitness-demo')
    ex=sp.add_parser('export',help='export GitHub-ready Markdown from report.json'); ex.add_argument('report'); ex.add_argument('--out')
    tr=sp.add_parser('torch-trace',help='run a PyTorch script with per-op synchronization'); tr.add_argument('script'); tr.add_argument('args',nargs=argparse.REMAINDER)
    co=sp.add_parser('compare',help='compare JSON numerical output from candidate and oracle commands'); co.add_argument('--candidate',required=True); co.add_argument('--oracle',required=True); co.add_argument('--atol',type=float,default=1e-5); co.add_argument('--rtol',type=float,default=1e-4); co.add_argument('--out',default='kernelwitness-compare')
    a=p.parse_args(argv)
    if a.sub=='compare':
        d=compare_commands(a.candidate,a.oracle,a.atol,a.rtol,out_dir=a.out); echo(f'match={d.equal} max_abs={d.max_abs} max_rel={d.max_rel} path={d.path}'); return 0 if d.equal else 1
    return {'doctor':lambda:_doctor(a.json),'run':lambda:_run(a),'minimize':lambda:_minimize(a),'demo':lambda:_demo(a),'export':lambda:_export(a),'torch-trace':lambda:run_script(a.script,a.args)}[a.sub]()

if __name__=='__main__': raise SystemExit(main())
