from __future__ import annotations
import html, json, shlex
from pathlib import Path
from .models import RunReport

def _e(x): return html.escape(str(x))

def github_markdown(r: RunReport) -> str:
    gpu=r.environment.gpu.get('name','No NVIDIA GPU detected')
    lines=[
        '### KernelWitness reproduction','',
        f'- **Failure:** {r.classification.title} (`{r.classification.kind}`)',
        f'- **Reproduction:** {r.reproduced}/{r.total_attempts}',
        f'- **GPU:** {gpu}',
        f"- **Command:** `{' '.join(shlex.quote(x) for x in r.command)}`",
    ]
    if r.sanitizer_findings:
        f=r.sanitizer_findings[0]
        lines += [f'- **Sanitizer:** {f.tool}: {f.error}', f'- **Kernel:** `{f.kernel or "unknown"}`']
    lines += ['', 'Generated by [KernelWitness](https://github.com/mneha05/kernelwitness).']
    return '\n'.join(lines)+'\n'

CSS='''
*{box-sizing:border-box}body{margin:0;background:#090B12;color:#f6f7fb;font:15px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;background-image:radial-gradient(circle at 80% 0,#16234d 0,transparent 28%),radial-gradient(circle at 10% 15%,#2a1832 0,transparent 22%)}
.wrap{max-width:1180px;margin:auto;padding:42px 24px 80px}.top{display:flex;justify-content:space-between;gap:22px;align-items:end;margin-bottom:28px}.brand{font:700 12px/1 ui-monospace,monospace;letter-spacing:.2em;color:#49E6B4}h1{font-size:clamp(38px,7vw,82px);line-height:.92;margin:12px 0 10px;letter-spacing:-.06em}.sub{color:#a8b1c3;max-width:720px;font-size:18px}.pill{padding:9px 13px;border:1px solid #2d3851;border-radius:99px;background:#0f1420;color:#c9d1df;font:12px ui-monospace,monospace}.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:18px}.card{background:linear-gradient(180deg,#121827ee,#0d111bee);border:1px solid #232b3b;border-radius:22px;padding:22px;box-shadow:0 22px 80px #0007}.hero{grid-column:1/-1;display:grid;grid-template-columns:1fr auto;align-items:center;gap:18px}.failure{font-size:31px;font-weight:750;letter-spacing:-.03em}.kind{color:#FF7FB7;font:12px ui-monospace,monospace;text-transform:uppercase;letter-spacing:.12em}.score{font-size:46px;font-weight:800;color:#FFC468}.muted{color:#8993A8}h2{margin:0 0 16px;font-size:18px}.timeline{display:grid;gap:9px}.launch{display:grid;grid-template-columns:100px 1fr auto;gap:12px;align-items:center;border:1px solid #252c3c;border-radius:13px;padding:11px 13px;background:#0b0f18}.launch.ok{border-left:3px solid #49E6B4}.launch.bad{border-left:3px solid #FF6B78}.launch span,.launch small{font:12px ui-monospace,monospace;color:#8d97aa}.finding{border:1px solid #283146;border-radius:16px;padding:16px;background:#0d121e}.eyebrow{font:11px ui-monospace,monospace;color:#7C9CFF;text-transform:uppercase;letter-spacing:.14em}.finding h3{margin:8px 0 14px;font-size:19px}.kv{display:grid;grid-template-columns:70px 1fr;gap:7px 12px}.kv span{color:#7f899c}code,pre{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}code{color:#d8e0ee}table{border-collapse:collapse;width:100%;font-size:13px}td{padding:8px;border-bottom:1px solid #202737;vertical-align:top}.yes{color:#49E6B4}.no{color:#697387}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#070a10;border:1px solid #202737;border-radius:14px;padding:15px;color:#bec9da;max-height:340px;overflow:auto}.empty{color:#788297;border:1px dashed #2a3142;padding:18px;border-radius:14px}a{color:#7C9CFF}@media(max-width:780px){.grid{grid-template-columns:1fr}.hero{grid-template-columns:1fr}.top{align-items:start;flex-direction:column}.launch{grid-template-columns:78px 1fr}.launch small{grid-column:2}}
'''

TEMPLATE='''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KernelWitness report</title><style>__CSS__</style></head><body><div class="wrap">
<div class="top"><div><div class="brand">KERNELWITNESS / CUDA FAILURE AUTOPSY</div><h1>__TITLE__</h1><div class="sub">__GPU__ · Python __PY__ · __PLATFORM__</div></div><div class="pill">__DATE__ UTC</div></div>
<div class="grid"><section class="card hero"><div><div class="kind">__KIND__</div><div class="failure">Failure reproduced __REP__ of __TOTAL__ attempts</div><p class="muted">__EVIDENCE__</p></div><div><div class="score">__CONF__%</div><div class="muted">classifier confidence</div></div></section>
<section class="card"><h2>Reproduction timeline</h2><div class="timeline">__ATTEMPTS__</div></section><section class="card"><h2>Sanitizer findings</h2>__FINDINGS__</section>
<section class="card"><h2>Environment</h2><table>__TOOLS__</table></section><section class="card"><h2>Command</h2><pre>__COMMAND__</pre><p class="muted">Secrets and home-directory paths are redacted by default.</p></section>
<section class="card"><h2>stdout</h2><pre>__STDOUT__</pre></section><section class="card"><h2>stderr</h2><pre>__STDERR__</pre></section></div></div></body></html>'''

def render(r: RunReport, out_dir: str|Path) -> Path:
    out=Path(out_dir); out.mkdir(parents=True,exist_ok=True)
    (out/'report.json').write_text(json.dumps(r.to_dict(),indent=2),encoding='utf-8')
    (out/'github.md').write_text(github_markdown(r),encoding='utf-8')
    attempts=''.join('<div class="launch %s"><span>attempt %s</span><b>%s</b><small>%.2fs · rc=%s</small></div>' % ('bad' if a.classification and a.classification.kind!='success' else 'ok', a.index, _e(a.classification.title if a.classification else ''), a.duration_s, _e(a.returncode)) for a in r.attempts)
    findings=''.join('<article class="finding"><div class="eyebrow">%s</div><h3>%s</h3><div class="kv"><span>kernel</span><code>%s</code><span>source</span><code>%s</code><span>thread</span><code>%s</code><span>block</span><code>%s</code></div></article>' % (_e(f.tool),_e(f.error),_e(f.kernel or 'unknown'),_e(f.source or 'unavailable'),_e(f.thread or '—'),_e(f.block or '—')) for f in r.sanitizer_findings) or '<div class="empty">No structured sanitizer finding was captured for this run.</div>'
    tools=''.join('<tr><td>%s</td><td class="%s">%s</td><td>%s</td></tr>' % (_e(t.name),'yes' if t.available else 'no','available' if t.available else 'missing',_e(t.version)) for t in r.environment.tools)
    values={
      '__CSS__':CSS,'__TITLE__':_e(r.classification.title),'__GPU__':_e(r.environment.gpu.get('name','No NVIDIA GPU detected')),'__PY__':_e(r.environment.python),'__PLATFORM__':_e(r.environment.platform),'__DATE__':_e(r.created_at[:19].replace('T',' ')),'__KIND__':_e(r.classification.kind),'__REP__':str(r.reproduced),'__TOTAL__':str(r.total_attempts),'__EVIDENCE__':_e(' '.join(r.classification.evidence[:2]) or 'The process outcome was classified from return code and captured output.'),'__CONF__':str(round(r.classification.confidence*100)),'__ATTEMPTS__':attempts,'__FINDINGS__':findings,'__TOOLS__':tools,'__COMMAND__':_e(' '.join(shlex.quote(x) for x in r.command)),'__STDOUT__':_e(r.attempts[-1].stdout[-5000:] if r.attempts and r.attempts[-1].stdout else '(empty)'),'__STDERR__':_e(r.attempts[-1].stderr[-5000:] if r.attempts and r.attempts[-1].stderr else '(empty)')}
    doc=TEMPLATE
    for k,v in values.items(): doc=doc.replace(k,v)
    p=out/'index.html'; p.write_text(doc,encoding='utf-8'); return p
